### ISSUE TITLE
Transfer and workerData?

### ISSUE THREAD

**Issue by ronag** [poolifier/poolifier#767]
In Piscina we can pass a  `transferList` option to `run` to pass transferable objects such as message ports and buffers to the worker. This seems to be missing in poolifier?

Also it's possibile to provide `workerData` to the pool factory which will make data available for each thread.

**Comment by ronag** [comment]
I'm trying to move from Piscina to poolifier. However, the following code does not (as far as I can see) have comparable functionality.

```
const worker = new Piscina({
  ...,
  workerData: { stateBuffer: new ArrayBuffer(...) }
})

worker.run({ statusPort }, { transferList: [statusPort], signal })
```

**Comment by jerome-benoit** [comment]
Poolifier currently does not offer any ease at the API level for shared buffer handling in `worker-threads` pool. The rationale is that `cluster` module does not offer similar feature. 
You can still use share array buffer with `worker-threads` pool in poolifier, but you have to do it yourself: 

- give a shared array buffer in workerData once to all workers
- use it to transfer information between workers and main thread with a home made message handler

**Comment by jerome-benoit** [comment]
Is the code base publically available? 
I would like to have a look at it to fully understand the requirements for `shared memory` with `worker-threads`.

**Comment by ronag** [comment]
> Is the code base publically available?

No. It basically to send status information back and forth with the worker and its jobs.

**Comment by jerome-benoit** [comment]
> > Is the code base publically available?
> 
> No. It basically to send status information back and forth with the worker and its jobs.

Do you have any concurrency issues on them (using atomics)?
Do you use it because of broadcasting needs between workers? 

If the primary shared buffer usage is only to have a request/response on a per task basis, I do not think it's necessary. The performance gain does not worth the added complexity with latest node.js LTS. And broadcasting can be done with a broadcast channel. 
The shared buffer usage is really needed if you need to maintain information that must be updated, read, ... between workers(/main thread) with concurrency issues requiring atomics usage.
Did you evaluate performance with piscina with and without the shared array buffer usage?

**Comment by ronag** [comment]
Yes, message channels in NodeJS are incredibly slow and not an option.

**Comment by jerome-benoit** [comment]
> Yes, message channels in NodeJS are incredibly slow and not an option. Were a major bottleneck when profiling our application and we had to move away from them.

Is it still relevant with node 18.x and 20.x? 

I use broadcast channel in https://github.com/SAP/e-mobility-charging-stations-simulator with more than 10 000 receivers/emetters without any performance issue. Message channels are not really used, tasks are running forever.

**Comment by jerome-benoit** [comment]
> > Is it still relevant with node 18.x and 20.x?
> 
> Yes, nothing has been done in regards to this in those versions.
> 

Ok, so it makes sense to add a shared buffer handling API to poolifier for `worker-threads` pool. I need to think a bit about it to make it thread-safe, optional and not invasive
The current code in poolifier rely on message channel to maintain tasks usage statistics, so I guess high tasks submission rate will impact performance because of their maintenance. 

> > I use broadcast channel in [SAP/e-mobility-charging-stations-simulator](https://github.com/SAP/e-mobility-charging-stations-simulator) with more than 10 000 receivers/emitters without any performance issue. Message channels are not really used, tasks are running forever.
> 
> How many messages are you send per second over the broadcast channel? It's not really the number of receive/emitters that matter, it's the number of messages sent.

Message rate is not enough to reach a bottleneck on broadcast message channel visible during profiling.

**Comment by jerome-benoit** [comment]
The proper solution will take some times to implement for both pool types. 

Until I have time to do, I can probably implement the similar API as piscina for shared buffer handling to:
+ worker-threads pool only
+ ease migration from piscina
+ close scalability issue with messaging 

I do not really understand the transfer list needs and how it's related to shared buffer usage.

**Comment by ronag** [comment]
Transfer list is unrelated. Just a different missing feature.

**Comment by jerome-benoit** [comment]
> Transfer list is unrelated. Just a different missing feature.

For shared buffer, I do see how to implement a shared memory abstraction with use to use API and optional threads safety on top of it for worker-threads and on top of message passing for cluster worker. 

But for transferable object, I do not see how to do it without internal support in the worker implementation type: cluster does not offer it.
